name: "Vehicle Digital Twin Feedback Loop"
description: Repository for Vehicle Digital Twin Feedback Loop

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aws-terraform-deployment
  description: Deployment to AWS using Terraform
spec:
  type: terraform
  lifecycle: experimental
  owner: everyone
  provides:
    - infrastructure
  template:
    path: vehicle-ts/src/server.ts
  config:
    source: vehicle-ts/src/Dockerfile
    variables:
      region: us-west-2
      # Add any other variables required by your Terraform script

# Add any other sections or configurations you require for your repository
