# app-config.yaml

name: Vehicle Digital Twin Feedback Loop
description: Repository for Vehicle Digital Twin Feedback Loop

componentMetadata: &componentMetadata
  name: aws-terraform-deployment-mongo
  description: Deployment to AWS using Terraform

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: *componentMetadata
spec:
  type: terraform
  lifecycle: experimental
  owner: everyone
  provides:
    - infrastructure
  template:
    path: vehicle-ts/src/server.ts
  config:
    source: "your-terraform-module-source"
    variables:
      region: us-west-2
      # Add any other variables required by your Terraform script

# Add any other sections or configurations you require for your repository
