apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Vehicle-Digital-Twin-Feedback-Loop
  annotations:
    github.com/project-slug: jamesenki/Vehicle-Digital-Twin-Feedback-Loop
spec:
  repositories: 
   - url: https://github.com/jamesenki/Vehicle-Digital-Twin-Feedback-Loop
  lifecycle: experimental
  owner: everyone
